version: '3.5'

services:
  sourceadapter1:
    image: sourceadapter1:latest
    container_name: sourceadapter1
    ports:
      - 8080:8080
  sinkadapter1:
    image: sinkadapter1:latest
    container_name: sinkadapter1
    ports:
      - 8081:8080
  message-audit-ingester:
    image: message-audit-ingester:latest
    container_name: message-audit-ingester
    ports:
      - 8082:8080
  sinkadapter2:
    image: sinkadapter2:latest
    container_name: sinkadapter2
    ports:
      - 8083:8080