version: '3.5'

services:
  sinkadapter1:
    image: sinkadapter1:latest
    container_name: sinkadapter1
    ports:
      - 8081:8080
  sinkadapter2:
    image: sinkadapter2:latest
    container_name: sinkadapter2
    ports:
      - 8083:8080